### PR TITLE
Support Slack Notification

### PR DESCRIPTION
**Pull request by chinvib66**
# Support Slack Notification

Added support for Slack Notification using Slack App Webhook. 
Supports custom notification message.

Addresses Issue #14

### CODE REVIEW

**Comment by mridhul** [comment]
@chinvib66 Thanks for the PR
For any failues, can we capture the output and send it to the slack ?

**Comment by chinvib66** [comment]
In `entrypoint.sh` lines [94-98](https://github.com/intuit/cfn-deploy/blob/9111f3307d830fbaf0a220c54e90d98c2d6019e6/entrypoint.sh#L94), the variable named `stack_output`. 

Shall I send this `stack_output` value in slack message?

Also, I see only the lines 94-98 where failure is noted. Is there any other location, where the action might fail and I have missed it?

**Comment by chinvib66** [comment]
> 
> In `entrypoint.sh` lines [94-98](https://github.com/intuit/cfn-deploy/blob/9111f3307d830fbaf0a220c54e90d98c2d6019e6/entrypoint.sh#L94), the variable named `stack_output`.
> 
> Shall I send this `stack_output` value in slack message?
> 
> Also, I see only the lines 94-98 where failure is noted. Is there any other location, where the action might fail and I have missed it?

@mridhul any thoughts on this?

**Comment by mridhul** [comment]
@chinvib66 : yes, that would be ideal. We can send that stack_output. Could you please share me a screenshot of the stack_output ?

**Comment by chinvib66** [comment]
@mridhul I'm afraid, I wouldn't be able to test the github action, since I don't have an aws account/aws dependent project; thus wouldn't be able to provide stack output. 

It would be helpful if you could provide stack output from some existing project's gh action log 
or
I'll complete this PR and you can verify the slack message while testing out the PR.

**Pull request closed without merging**
