### PR TITLE
Typos & formatting

### PR DESCRIPTION
**Pull request by kornicameister**
- fixes couple of typos
- introduces clearly visible sections

### CODE REVIEW

**Comment by kornicameister** [comment]
@mridhul no worries, we do that all the time.

**Comment by mridhul** [comment]
Hope you are finding the action useful. Any plans to contribute or any feature request ?

**Comment by kornicameister** [comment]
not at a moment. GA are being investigates against usability in incoming project. Maybe we will need extension here, maybe we will not even use this action or any action for cloud formation. 

will see ;-))

**Comment by mridhul** [comment]
Got it. All the best

**Pull request merged**
